ensembl_gtf: /nfs/users/nfs_k/ka8/scratch/annotations/GRCh38/genes/Ensembl_87/Homo_sapiens.GRCh38.87.gtf
reference_genome: /nfs/users/nfs_k/ka8/scratch/annotations/GRCh38/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa 
salmon_ensembl_index: /nfs/users/nfs_k/ka8/scratch/annotations/GRCh38/genes/Ensembl_87/salmon_index_87
star_index: /nfs/users/nfs_k/ka8/scratch/annotations/GRCh38/STAR_index_87
vcf_file: /nfs/users/nfs_k/ka8/scratch/projects/macrophage-gxe-study/genotypes/SL1344/hipsci.wec.gtarray.HumanCoreExome-12_v1_0.858samples.20141111.genotypes.GRCh38.sorted.filtered.vcf.gz
chromosome_lengths: /lustre/scratch117/cellgen/team170/ka8/annotations/GRCh38/bt2-index/chromosome_lengths.txt
samples: [aipt_A, aipt_B]
annotations: ["reviseAnnotations.grp_1_contained","reviseAnnotations.grp_1_upstream","reviseAnnotations.grp_1_downstream","reviseAnnotations.grp_2_contained","reviseAnnotations.grp_2_upstream","reviseAnnotations.grp_2_downstream"]
study: salmonella
libType: ISR

#Quantification
leafcutter_root: "/nfs/users/nfs_k/ka8/software/leafcutter"

#QTL mapping 
conditions: ["Ctrl", "AcLDL", "Diff"]
n_batches: 250
qtl_vcf: "/nfs/users/nfs_k/ka8/scratch/projects/macrophage-gxe-study/genotypes/acLDL/imputed_20151005/imputed.70_samples.sorted.filtered.named.INFO_07.vcf.gz"
cis_window: 100000
nominal_cis_window: 500000
annot_type: ["ensembl_87", "reviseAnnotations", "leafcutter"]

#Colocalisation
coloc_phenotypes: ["ensembl_87", "reviseAnnotations", "leafcutter", "featureCounts"]
gwas_dir: "/nfs/users/nfs_k/ka8/scratch/datasets/Inflammatory_GWAS/"
coloc_window: 2e5
gwas_traits: ["AD","CEL_2010","CEL","CD","IBD","UC","MS","NAR","PBC","PS","RA_2012","RA","SCZ","SLE","T1D","T1D_2","T2D_1","T2D","UC_2012","UC_2014","CAD","MI","CRE","CRP","GLU","HDL","HGB","HOMA_b","HOMA_ir","IL6","INS","MCHC","MCH","MCV","PCV","PLT","RBC","TC","TG","UA","WBC","LDL","CAD_2017"]




