samples: [sample_01, sample_02, sample_03, sample_04, sample_05, sample_06, sample_07, sample_08, sample_09, sample_10, sample_11, sample_12, sample_13, sample_14, sample_15, sample_16, sample_17, sample_18, sample_19, sample_20, sample_21, sample_22, sample_23, sample_24, sample_25, sample_26, sample_27, sample_28, sample_29, sample_30, sample_31, sample_32, sample_33, sample_34, sample_35, sample_36, sample_37, sample_38, sample_39, sample_40, sample_41, sample_42, sample_43, sample_44, sample_45, sample_46, sample_47, sample_48, sample_49, sample_50, sample_51, sample_52, sample_53, sample_54, sample_55, sample_56, sample_57, sample_58, sample_59, sample_60, sample_61, sample_62, sample_63, sample_64, sample_65, sample_66, sample_67, sample_68, sample_69, sample_70, sample_71, sample_72, sample_73, sample_74, sample_75, sample_76, sample_77, sample_78, sample_79, sample_80, sample_81, sample_82, sample_83, sample_84, sample_85, sample_86]
#samples: [sample_01, sample_02]
#annotations: ["extended_transcripts","original_transcripts","txrevise_upstream","txrevise_contained","txrevise_downstream"]
annotations: ["one_transcripts","both_transcripts","txrevise_upstream_both","txrevise_downstream_both"]
libType: ISF
reference_genome: /gpfs/rocket/home/a72094/annotations/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa
whippet_index: processed/annotations/whippet_index/both_transcripts


#HISAT2 config
hisat2_index: /gpfs/hpchome/a72094/rocket/annotations/GRCh38/hisat2_index_v90/Homo_sapiens.GRCh38.dna.primary_assembly
hisat2_flags: ""

dexseq_gtf: "processed/annotations/gff/both_transcripts.flat.gtf"
